import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../components/layout/Header";
import AppProvider from "../components/AppContext";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="mx-auto">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AppProvider>
              <Toaster />
              <Header />
              {children}
              <footer className="border-t p-8 text-center text-gray-500 mt-16">
                &copy; 2024 Company, Inc. All rights reserved.
              </footer>
            </AppProvider>
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
